### ISSUE TITLE
HDrezka обновления

### ISSUE THREAD

**Issue by dotstal** [ShutovPS/RemoteFork.Plugins#3]
Сайт сменил адрес, не могли бы Вы обновить плагин?

**Comment by ShutovPS** [comment]
Что бы не ждать, пока я поправлю плагин, можно самостоятельно изменить параметры в файле **hdrezka.json**:
- "Site" на работающий адрес сайта.
- "ExtList" на "(#EXT-X.*?=)(\\d+x\\d+)([\\s\\S]*?)(http.?:.*)"

И перезапустить rf.

**Comment by dotstal** [comment]
После перезагрузки все изменения исчезнут, я так понимаю он заново восстановит из .dll

**Comment by ShutovPS** [comment]
Нет, настройки сбрасываются только после обновления плагина.

**Comment by ShutovPS** [comment]
Поправил в новой версии: https://github.com/ShutovPS/RemoteFork.Plugins/releases/tag/hdrezka.0.0.12
